### ISSUE TITLE
Quarry Crashing 1.19.2

### ISSUE THREAD

**Issue by turtlez142** [OneLemonyBoi/MiniUtilities#152]
**Describe the bug**

soon as the quarry gets a power supply it crashes

**Mod Info (please complete the following information):**
 - Forge: 
 - MC Version: 1.19.2
 - Mod Version: 3.0.0

[crash-2023-09-19_19.42.51-server.txt](https://github.com/OneLemonyBoi/MiniUtilities/files/12665518/crash-2023-09-19_19.42.51-server.txt)

**Comment by AndyDL24** [comment]
Hi, yes same thing for me too.
[crash-2023-10-06_00.14.29-server.txt](https://github.com/OneLemonyBoi/MiniUtilities/files/12824984/crash-2023-10-06_00.14.29-server.txt)

**Comment by lilrajoo** [comment]
happens in 1.20.1 version too

**Comment by GaalFlorian** [comment]
I appear to have found the root cause of the issue on 1.20.1 and the fix is quite simple. I tested it in one of my worlds and the crashing stopped from it.

In the QuantumQuarryTile class, serverTick function there is a loop trying to go through 27 inventory slots in the quantum quarry. Reducing it to the 9 slots that are actually available, fixes this crash.
Image with the modified value:

![image](https://github.com/OneLemonyBoi/MiniUtilities/assets/79801028/0df7c7c1-0393-41a0-bdc8-538ce8e8e991)

**Comment by OneLemonyBoi** [comment]
fixed in dev, release coming soon
